# Generated by Django 2.0.7 on 2018-07-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platekey',
            name='row',
            field=models.CharField(max_length=1),
        ),
    ]
