# Generated by Django 2.0.6 on 2018-06-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='plateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1)),
                ('column', models.PositiveIntegerField()),
                ('concentration', models.FloatField(null=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosdb.compound')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosdb.plateLayout')),
            ],
        ),
    ]
