# Generated by Django 2.0.6 on 2018-06-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='movie_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mosdb.movieFile'),
        ),
        migrations.AddField(
            model_name='moviefile',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mosdb.experiment'),
        ),
    ]
