# Generated by Django 2.0.6 on 2018-06-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosdb', '0002_compound_platekey'),
    ]

    operations = [
        migrations.CreateModel(
            name='genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='genotype',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosdb.species'),
        ),
    ]
